### ISSUE TITLE
Is it possible for ghostie to receive new notifications in real-time rather than polling every minute?

### ISSUE THREAD

**Issue by eval-exec** [attriaayush/ghostie#15]
It would be beneficial if ghostie could instantly receive new notifications instead of experiencing a delay of one minute.

Thank you.

**Comment by attriaayush** [comment]
Apologies for the delayed response.

I don't think Github APIs allow for websocket connections to get real time updates (I could be wrong). 

`ghostie` supports for users to configure the frequency of polling by using `ghostie configure`. However, the current logic only supports `minute` as a basic time unit. If you would like `ghostie` to poll Github every few seconds, it should be a relatively small change to use `second` as the base time unit. 

If you can open a PR to contribute the change, I will be more than happy to review it.

**Comment by attriaayush** [comment]
Going to close this issue for now.
